# Generated by Django 5.1.6 on 2025-02-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=0, upload_to='Files')),
                ('code', models.CharField(max_length=6)),
                ('qr', models.FileField(default=0, upload_to='QRcodes')),
                ('inserttime', models.DateTimeField()),
            ],
        ),
    ]
